qatrack/accounts/urls.py
from django.conf import settings
from django.conf.urls.defaults import patterns, include, url
import views


urlpatterns = patterns('',
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': settings.LOGIN_URL}),
    url(r'^details/$', views.AccountDetails.as_view(), name="account-details"),
    url(r'^', include('registration.urls')),
)

qatrack/qa/urls.py
from django.conf.urls.defaults import patterns, include, url

from views import base, perform, review, charts, backup

from qatrack.qa import api
from tastypie.api import Api

v1_api = Api(api_name="v1")
resources = [
    api.TestListResource(),
    api.TestResource(),
    api.TestInstanceResource(),
    api.TestListInstanceResource(),
    api.ValueResource(),
    api.FrequencyResource(),
    api.StatusResource(),
    api.ReferenceResource(),
    api.CategoryResource(),
    api.ToleranceResource(),
    api.UnitResource(),
    api.ModalityResource(),
    api.UnitTypeResource(),
    api.GroupResource(),
]
for resource in resources:
    v1_api.register(resource)


urlpatterns = patterns('',

    url(r"^$", base.UTCList.as_view(), name="all_lists"),

    # view for composite calculations via ajax
    url(r"^composite/$", perform.CompositeCalculation.as_view(), name="composite"),

    # view for uploads via ajax
    url(r"^upload/$", perform.Upload.as_view(), name="upload"),

    # api urls
    url(r"^api/", include(v1_api.urls)),

    url(r"^charts/$", charts.ChartView.as_view(), name="charts"),
    url(r"^charts/data/$", charts.BasicChartData.as_view(), name="chart_data"),
    url(r"^charts/control_chart.png$", charts.ControlChartImage.as_view(), name="control_chart"),

    # overall program status
    url(r"^review/$", review.Overview.as_view(), name="overview"),
    url(r"^review/due-dates/$", review.DueDateOverview.as_view(), name="overview_due_dates"),

    # review utc's
    url(r"^review/all/$", review.UTCReview.as_view(), name="review_all"),
    url(r"^review/utc/(?P<pk>\d+)/$", review.UTCInstances.as_view(), name="review_utc"),
    url(r"^review/frequency/$", review.ChooseFrequencyForReview.as_view(), name="choose_review_frequency"),
    url(r"^review/frequency/(?P<frequency>[/\w-]+?)/$", review.UTCFrequencyReview.as_view(), name="review_by_frequency"),
    url(r"^review/unit/$", review.ChooseUnitForReview.as_view(), name="choose_review_unit"),
    url(r"^review/unit/(?P<unit_number>[/\d]+)/$", review.UTCUnitReview.as_view(), name="review_by_unit"),

    # test list instances
    url(r"^session/details/$", base.TestListInstances.as_view(), name="complete_instances"),
    url(r"^session/details/(?P<pk>\d+)/$", review.TestListInstanceDetails.as_view(), name="view_test_list_instance"),
    url(r"^session/review/(?P<pk>\d+)/$", review.ReviewTestListInstance.as_view(), name="review_test_list_instance"),
    url(r"^session/unreviewed/$", review.Unreviewed.as_view(), name="unreviewed"),
    url(r"^session/in-progress/$", perform.InProgress.as_view(), name="in_progress"),
    url(r"^session/continue/(?P<pk>\d+)/$", perform.ContinueTestListInstance.as_view(), name="continue_tli"),
    url(r"^session/edit/(?P<pk>\d+)/$", perform.EditTestListInstance.as_view(), name="edit_tli"),


    url(r"^unit/$", perform.ChooseUnit.as_view(), name="choose_unit"),
    url(r"^utc/perform/(?P<pk>\d+)/$", perform.PerformQA.as_view(), name="perform_qa"),

    url(r"^unit/(?P<unit_number>[/\d]+)/frequency/(?P<frequency>[/\w-]+?)/$", perform.UnitFrequencyList.as_view(), name="qa_by_frequency_unit"),
    url(r"^unit/(?P<unit_number>[/\d]+)/$", perform.UnitList.as_view(), name="qa_by_unit"),

    url(r"^frequency/(?P<frequency>[/\w-]+)/unit/(?P<unit_number>[/\d]+)/$", perform.UnitFrequencyList.as_view(), name="qa_by_unit_frequency"),
    url(r"^frequency/(?P<frequency>[/\w-]+?)/$", perform.FrequencyList.as_view(), name="qa_by_frequency"),


    url(r"^backup/$", backup.PaperFormRequest.as_view(), name="qa_paper_forms_request"),
    url(r"^backup/paper/$", backup.PaperForms.as_view(), name="qa_paper_forms"),

)

qatrack/urls.py
from django.conf import settings
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.base import TemplateView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    url(r'^$', TemplateView.as_view(template_name="homepage.html"), name="home"),

    url(r'^accounts/', include('qatrack.accounts.urls')),
    url(r'^qa/', include('qatrack.qa.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'^', include('genericdropdown.urls')),

)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:],
         'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    )

qatrack/accounts/models.py
from django.conf import settings

from django.contrib.auth.models import User, Group
from django.db.models.signals import post_save
from django.dispatch import receiver


#----------------------------------------------------------------------
@receiver(post_save, sender=User)
def add_to_default_groups(sender, instance, created, **kwargs):
    """
    if any default groups are defined in settings the user will
    be added to them.
    """

    if created:
        group_names = getattr(settings, "DEFAULT_GROUP_NAMES", [])

        for group_name in group_names:

            group, _ = Group.objects.get_or_create(name=group_name)
            instance.groups.add(group)
            instance.save()

qatrack/contacts/models.py
from django.db import models


#============================================================================
class Contact(models.Model):
    """basic contact number"""
    name = models.CharField(max_length=256)
    number = models.CharField(max_length=256)
    description = models.TextField()

    #----------------------------------------------------------------------
    def __unicode__(self):
        return "%s : %s " % (self.name, self.number)

qatrack/notifications/models.py
from django.db import models
from django.contrib.auth.models import Group

# this import has to be here so that the signal handlers get registered
import handlers


TOLERANCE = 10
ACTION = 20

WARNING_LEVELS = (
    (TOLERANCE, "Notify on Tolerance or Action"),
    (ACTION, "Notify on Test at Action level only"),
)

#============================================================================


class NotificationSubscription(models.Model):

    group = models.ForeignKey(Group, unique=True)

    warning_level = models.IntegerField(choices=WARNING_LEVELS)

    #----------------------------------------------------------------------
    def __unicode__(self):
        return "<NotificationSubscription(%s)>" % self.group.name

qatrack/theme_bootstrap/models.py
# This file is intentionally left blank to allow Django to load the app.

qatrack/qa/views/forms.py
from django import forms
from django.core.validators import MaxLengthValidator
from django.forms.models import inlineformset_factory
from django.forms.widgets import RadioSelect, Select, HiddenInput
from django.utils import timezone
from django.utils.translation import ugettext as _

from django.conf import settings

from .. import models

from qatrack.qa import utils

BOOL_CHOICES = [(0, "No"), (1, "Yes")]


#====================================================================================
class UserFormsetMixin(object):
    """A mixin to add a user object to every form in a formset (and the formset itself)"""

    #----------------------------------------------------------------------
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user")
        super(UserFormsetMixin, self).__init__(*args, **kwargs)

    #---------------------------------------------------------------------------
    def _construct_forms(self):
        """add user to all children"""
        self.forms = []
        for i in xrange(self.total_form_count()):
            f = self._construct_form(i)
            f.user = self.user
            self.forms.append(f)


#============================================================================
class TestInstanceWidgetsMixin(object):
    """
    Mixin to override default TestInstance field widgets and validation
    based on the Test type.
    """

    #----------------------------------------------------------------------
    def clean(self):
        """do some custom form validation"""
        cleaned_data = super(TestInstanceWidgetsMixin, self).clean()

        if self.in_progress:
            return cleaned_data

        skipped = cleaned_data.get("skipped")
        comment = cleaned_data.get("comment")
        value = cleaned_data.get("value", None)
        string_value = cleaned_data.get("string_value", None)

        # force user to enter value unless skipping test
        if value is None and not string_value and not skipped:
            self._errors["value"] = self.error_class(["Value required if not skipping"])
        elif (value is not None or string_value) and skipped:
            self._errors["value"] = self.error_class(["Clear value if skipping"])

        if not self.user.has_perm("qa.can_skip_without_comment") and skipped and not comment:
            self._errors["skipped"] = self.error_class(["Please add comment when skipping"])
            del cleaned_data["skipped"]

        if value is None and skipped and "value" in self.errors:
            del self.errors["value"]

        return cleaned_data

    #---------------------------------------------------------------------------
    def set_value_widget(self):
        """add custom widget for boolean values (after form has been initialized)"""

        # temp store attributes so they can be restored to reset widget
        self.fields["string_value"].widget.attrs["class"] = "qa-input"
        self.fields["value"].widget.attrs["class"] = "qa-input"
        attrs = self.fields["value"].widget.attrs
        str_attrs = self.fields["string_value"].widget.attrs

        test_type = self.unit_test_info.test.type

        if test_type == models.BOOLEAN:
            self.fields["value"].widget = RadioSelect(choices=BOOL_CHOICES)
        elif test_type == models.MULTIPLE_CHOICE:
            self.fields["value"].widget = Select(choices=[("", "")] + self.unit_test_info.test.get_choices())
        elif test_type == models.UPLOAD:
            self.fields["string_value"].widget = HiddenInput()

        if test_type in (models.BOOLEAN, models.MULTIPLE_CHOICE):
            if hasattr(self, "instance") and self.instance.value is not None:
                self.initial["value"] = int(self.instance.value)

        self.fields["value"].widget.attrs.update(attrs)
        self.fields["string_value"].widget.attrs.update(str_attrs)

    #----------------------------------------------------------------------
    def disable_read_only_fields(self):
        """disable some fields for constant and composite tests"""
        if self.unit_test_info.test.type in (models.CONSTANT, models.COMPOSITE, ):
            self.fields["value"].widget.attrs["readonly"] = "readonly"
        elif self.unit_test_info.test.type in (models.STRING_COMPOSITE,):
            self.fields["string_value"].widget.attrs["readonly"] = "readonly"


#============================================================================
class CreateTestInstanceForm(TestInstanceWidgetsMixin, forms.Form):

    value = forms.FloatField(required=False, widget=forms.widgets.TextInput(attrs={"class": "qa-input"}))
    string_value = forms.CharField(required=False, validators=[MaxLengthValidator(models.MAX_STRING_VAL_LEN)])

    skipped = forms.BooleanField(required=False, help_text=_("Was this test skipped for some reason (add comment)"))
    comment = forms.CharField(widget=forms.Textarea, required=False, help_text=_("Show or hide comment field"))

    #---------------------------------------------------------------------------
    def __init__(self, *args, **kwargs):
        super(CreateTestInstanceForm, self).__init__(*args, **kwargs)
        self.in_progress = False
        self.fields["comment"].widget.attrs["rows"] = 2

    #----------------------------------------------------------------------
    def set_unit_test_info(self, unit_test_info):
        self.unit_test_info = unit_test_info
        self.set_value_widget()
        self.disable_read_only_fields()

    #----------------------------------------------------------------------
    def get_test_info(self):
        return {
            "reference": self.unit_test_info.reference,
            "tolerance": self.unit_test_info.tolerance,
            "unit_test_info": self.unit_test_info,
            "test": self.unit_test_info.test,
        }


#============================================================================
BaseTestInstanceFormSet = forms.formsets.formset_factory(CreateTestInstanceForm, extra=0)


class CreateTestInstanceFormSet(UserFormsetMixin, BaseTestInstanceFormSet):
    """
    Formset for entering all the test values for the TestList that a
    user is performing.
    """

    #----------------------------------------------------------------------
    def __init__(self, *args, **kwargs):
        """
        Set the UnitTestInfo object for each form in the formset and
        set initial values for any CONSTANT Test type.
        """

        unit_test_infos = kwargs.pop("unit_test_infos")

        initial = []
        for uti in unit_test_infos:

            init = {"value": None}

            if uti.test.type == models.CONSTANT:
                init["value"] = utils.to_precision(uti.test.constant_value, 4)

            initial.append(init)

        kwargs.update(initial=initial)

        super(CreateTestInstanceFormSet, self).__init__(*args, **kwargs)

        for form, uti in zip(self.forms, unit_test_infos):
            form.set_unit_test_info(uti)


#============================================================================
class UpdateTestInstanceForm(TestInstanceWidgetsMixin, forms.ModelForm):

    #============================================================================
    class Meta:
        model = models.TestInstance
        fields = ("value", "string_value", "skipped", "comment",)

    #----------------------------------------------------------------------
    def __init__(self, *args, **kwargs):

        super(UpdateTestInstanceForm, self).__init__(*args, **kwargs)
        self.fields["value"].required = False
        self.unit_test_info = self.instance.unit_test_info
        self.set_value_widget()
        self.disable_read_only_fields()

    #----------------------------------------------------------------------
    def get_test_info(self):
        return {
            "reference": self.instance.reference,
            "tolerance": self.instance.tolerance,
            "unit_test_info": self.instance.unit_test_info,
            "test": self.instance.unit_test_info.test,
        }


#============================================================================
BaseUpdateTestInstanceFormSet = inlineformset_factory(models.TestListInstance, models.TestInstance, form=UpdateTestInstanceForm, extra=0, can_delete=False)


class UpdateTestInstanceFormSet(UserFormsetMixin, BaseUpdateTestInstanceFormSet):
    pass


#============================================================================
class ReviewTestInstanceForm(forms.ModelForm):

    #============================================================================
    class Meta:
        model = models.TestInstance
        fields = ("status", )


#============================================================================
BaseReviewTestInstanceFormSet = inlineformset_factory(models.TestListInstance, models.TestInstance, form=ReviewTestInstanceForm, extra=0, can_delete=False)


class ReviewTestInstanceFormSet(UserFormsetMixin, BaseReviewTestInstanceFormSet):
    pass


#============================================================================
class BaseTestListInstanceForm(forms.ModelForm):
    """parent form for performing or updating a qa test list"""

    status = forms.ModelChoiceField(
        queryset=models.TestInstanceStatus.objects,
        initial=models.TestInstanceStatus.objects.default,
        required=False
    )

    work_completed = forms.DateTimeField(required=False)

    modified = forms.DateTimeField(required=False)

    #----------------------------------------------------------------------
    class Meta:
        model = models.TestListInstance
        exclude = ("day",)

    #----------------------------------------------------------------------
    def __init__(self, *args, **kwargs):
        super(BaseTestListInstanceForm, self).__init__(*args, **kwargs)

        for field in ("work_completed", "work_started"):
            self.fields[field].widget = forms.widgets.DateTimeInput()

qatrack/accounts/views.py
from django.views.generic.base import TemplateView
from qatrack.qa.models import PERMISSIONS


class AccountDetails(TemplateView):
    template_name = "registration/account.html"

    def get_context_data(self, **kwargs):

        context = super(AccountDetails, self).get_context_data(**kwargs)
        all_perms = self.request.user.get_all_permissions()
        permissions = []
        for category, perms in PERMISSIONS:
            category_perms = []
            for perm, title, desc in perms:
                category_perms.append((perm in all_perms, title, desc))

            permissions.append((category, category_perms))

        context["permissions"] = permissions

        return context

qatrack/notifications/views.py
# Create your views here.

qatrack/units/views.py
# Create your views here.

qatrack/templates/qa/due_date.html
<span class="label due-status {{unit_test_collection.due_status}}" data-timestamp="{{unit_test_collection.due_date|date:"U"}}">
    {% with unit_test_collection.due_date as due_date %}
        {% if due_date %}
            {{due_date|date:"DATE_FORMAT"}}
        {%else%}
            Not Due
        {%endif%}
    {% endwith %}
</span>

qatrack/templates/qa/frequency_choose_for_review.html
{% extends "site_base.html" %}
{% load staticfiles %}

{% block head_title %}Choose Frequency for Review{% endblock %}

{% block body %}
<div class="row-fluid">
    <div class="span12">
        <h2>Review QA By Frequency</h2>
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <em>Choose a frequency below to review test lists</em>
    </div>
</div>
<div class="row-fluid row-spacer">
    <div class="span12">
        <div class="btn-group">
            {% for freq in frequencies %}
                <button class="btn"><a href="{% url review_by_frequency frequency=freq.slug %}">{{freq.name}}</a></button>
            {% endfor %}
            <button class="btn"><a href="{% url review_by_frequency frequency="ad-hoc" %}">Ad hoc</a></button>
        </div>
        <script type="text/javascript">
            $(".btn").click(function(){
                window.location = $(this).find("a").attr("href");
            });
        </script>
    </div>
</div>

{% endblock %}

qatrack/templates/qa/history.html
{% load qa_tags %}
{% if history %}
{% with test=history.0.unit_test_info.test unit=history.0.unit_test_info.unit %}
        {% for hist in history %}
            {% if test.is_upload or test.is_string or test.is_string_composite %}
            <span class="history-value">
                    {{hist.value_display|safe}}
            </span>
            {% elif hist.work_completed and hist.pass_fail != "not_done" %}

                <span class="label {{hist.pass_fail}} history-value" title="Diff from ref={% if hist.diff_display %}{{hist.diff_display}}{%else%}N/A{%endif%};  {{hist.created_by}} on {{hist.work_completed}}; {{hist.status}}">
                        {{hist.value_display|safe}}
                </span>
            {% else %}
                <span class="label history-value" title="N/A">N/A</span>
            {% endif %}
        {% endfor %}
        {% if test.is_upload or test.is_string_type %}
        <i class="icon-picture"></i>
        {% else %}
        <a title="View chart of this data" target="_blank" href="{% url charts %}#units={{unit.pk}}&tests={{test.pk}}"><i class="icon-picture"></i></a>
        {% endif %}
    {% endwith %}
{% endif %}

qatrack/templates/qa/testlistinstance_form.html
{% extends "site_base.html" %}
{% load staticfiles %}

{% block head_title %}{% spaceless %}
    {% if test_list_instance %}
        Edit {{test_list_instance.unit_test_collection.unit.name}} : {{test_list_instance.test_list.name}}
    {% else %}
        Perform {{unit_test_collection.unit.name}} : {{test_list.name}}
    {% endif %}
{%endspaceless%}{% endblock %}

{% block page_style %}
    <link href="{% static "datepicker/css/datepicker.css" %}?v={{VERSION}}" rel="stylesheet">
{% endblock %}


{% load qa_tags %}

{% block script_base %}
    {{block.super}}

    <script type="text/javascript">
        var unit_test_infos = {{unit_test_infos|safe}};
    </script>
{% endblock script_base %}

{% block body %}

<div class="row-fluid">
    <div class="span12">
        <h3 class="pull-left">
            {% if test_list_instance %}
                Edit {{test_list_instance.unit_test_collection.unit.name}} : {{test_list_instance.test_list.name}}
            {% else %}
                Perform {{unit_test_collection.unit.name}} : {{test_list.name}}
            {% endif %}
            {% if test_list.description %}
            <a id="test-list-info-toggle" class="show-hide" title="Click to view description and general instructions for this test list"><i class="icon-info-sign" ></i></a>
            {% endif %}
        </h3>
        <div id="float-right-container">
            <div id="contact-container" class="alert alert-info">

                <span id="toggle-contacts" class="pull-right hand-cursor">
                    Contact Numbers <i class="icon-plus-sign"></i>
                </span>
                <div class="clearfix"></div>
                <div id="contacts" class="clearfix">
                    <hr/>
                    <dl class="dl-horizontal">
                        {% for contact in contacts %}
                            <dt><abbr title="{{contact.description}}">{{contact.name}}</abbr></dt>
                            <dd>{{contact.number}}</dd>
                        {% endfor %}
                    </dl>
                </div>
            </div>
        </div>
    </div>
</div>

{% if test_list.description %}
<div id="test-list-info" class="row-fluid" style="display:none;">
    <div class="span12">
        <pre >
            {{test_list.description|safe}}
        </pre>
    </div>
</div>
{% endif %}

{% if days and last_instance %}
    <div class="row-fluid">
        <div class="span12">
            <h5 class="pull-left">
                <em>Last done: {% if last_day %}Day {{last_day}} ({{last_instance.test_list.name}}){% else %}New list{%endif%}</em>
            </h5>
        </div>
    </div>
{% endif %}
<div class="row-fluid">
    <div class="span12" id="overall-qa-status">
        <div id="do-not-treat-top" class="alert alert-error do-not-treat">
            <strong>Do Not Treat! Call Physics.</strong>
        </div>
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <form class="nosubmit form-inline" id="qa-form" method="POST" action="" autocomplete="off">

            {% csrf_token %}
            <input type="hidden" id="test-list-id" value="{{test_list.pk}}"/>
            <input type="hidden" id="test-list-name" value="{{test_list.name}}"/>
            <input type="hidden" id="unit-id" value="{{unit_test_collection.unit.pk}}"/>
            <input type="hidden" id="unit-number" value="{{unit_test_collection.unit.number}}"/>
            <input type="hidden" id="cycle-day-number" value="{{current_day}}"/>

            <input type="hidden" id="pass-fail-only" value="{% if perms.qa.can_view_ref_tol %}no{% else %}yes{% endif %}"/>
            <input type="hidden" id="require-comment-on-skip" value="{% if perms.qa.can_skip_without_comment %}no{% else %}yes{% endif %}"/>

            <div id="admin_controls" class="well">

                {# display any form errors up top #}
                {% if form.errors %}
                    <div class="alert-message error">
                        {% for field in form%}
                                {% for error in field.errors %}
                                    <span class="alert-error help-block-inline ">{{field.label}} ::{{ error }}</span>
                                {% endfor %}
                        {% endfor %}
                    </div>
                    <hr/>
                {% endif %}

                {% if perms.qa.can_perform_subset %}

                    <div class="input-prepend input-append" id="category">
                        <label for="category_filter" class="add-on">
                            Categories:
                        </label>
                        <select id="category_filter" multiple="multiple" class="input-medium">
                            <option value="all" selected="selected">Show All</option>
                            {% for category in categories %}
                                <option value="{{category.pk}}">
                                    {{category.name}}
                                </option>
                            {% endfor %}
                        </select>
                    </div>
                {% endif %}

                <div class="date input-prepend input-append" id="work-started" data-date="{% now 'd-m-Y'%}" data-date-format="dd-mm-yyyy">
                    {% spaceless %}
                        <label for="id_work_started" class="add-on">
                            {{form.work_started.label}}:
                        </label>
                        {{form.work_started}}
                        {% if perms.qa.can_override_date %}
                            <span class="add-on"><i class="icon-calendar"></i></span>
                        {% endif %}
                    {% endspaceless %}
                </div>

                {% if perms.qa.can_override_date %}
                    <div class="date input-prepend input-append" id="work-completed" data-date="{% now 'd-m-Y'%}" data-date-format="dd-mm-yyyy">
                        <label for="id_work_completed" class="add-on">
                            {{form.work_completed.label}}:
                        </label>{{form.work_completed}}<span class="add-on"><i class="icon-calendar"></i></span>
                    </div>
                {% endif %}

                {% if perms.qa.can_review %}
                    <div class="input-prepend input-append" id="status">
                        <label for="id_status" class="add-on">
                            Set Status:
                        </label>{{form.status}}
                    </div>

                {% endif %}

                {% if days %}
                <div class="input-prepend" id="cycle-day-wrapper">
                    <label for="cycle-day" class="add-on">
                        Choose Day:
                    </label>
                    <select id="cycle-day" class="input-small" {% if not days %}disabled="disabled"{%endif%}>
                        <option value="next">Next scheduled</option>
                        {% for day in days %}
                            <option value="{{day}}" {% if day == current_day %}selected="selected"{% endif %}>
                                Day {{day}}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                {% endif %}

            </div>


            {% if formset.non_form_errors %}
                <div class="alert-message error">
                    {% for error in formset.non_form_errors %}
                        <span class="alert-error help-block-inline">{{ error }}</span>
                    {% endfor %}
                </div>
            {% endif %}


            {{formset.management_form}}

            <table id="perform-qa-table" class="qa-table table table-bordered table-striped table-condensed" >
                <thead>
                    <tr>
                        <th class="qa-category">Category</th>
                        <th class="qa-showproc qa-name">Name</th>
                        <th class="qa-value" width=100>Value</th>
                        <th class="qa-skip">Skip</th>
                        <th class="qa-status">Status</th>
                        <th class="qa-showcmt">Comment</th>
                        {% if perms.qa.can_view_ref_tol or perms.qa.can_view_history %}
                            {% if perms.qa.can_view_ref_tol %}
                                <th class="qa-reference">Reference</th>
                            {% endif %}
                            {% if perms.qa.can_view_history %}
                                <th class="qa-history">History<br/>
                                    {% for d in history_dates %}
                                        <span class="label history-label" title="{{d}}">{{d|date:"dMy"}}</span>
                                    {% endfor %}
                                <div></div></th>
                            {% endif %}
                        {% else %}
                            <th>&nbsp;<div></div></th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for test_form in formset %}
                        {% qa_value_form test_form include_history=perms.qa.can_view_history include_ref_tols=perms.qa.can_view_ref_tol test_info=test_form.get_test_info  %}
                    {% endfor %}
                </tbody>
            </table>

            <div class="row-fluid">
                <div class="span12">
                    <a id="toggle-gen-comment" class="btn pull-right" href="#" title="Click here to add a general comment about this set of tests"><i class="icon-edit"></i> Add Comment</a>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span12 qa-tli-comment">
                    {{form.comment}}
                </div>
            </div>

            <div class="row-fluid">
                <div class="span12" id="overall-qa-status">
                    <div id="do-not-treat-bottom" class="alert alert-error do-not-treat">
                        <strong>Do Not Treat! Call Physics.</strong>
                    </div>
                </div>
            </div>

            <div class="row-fluid">
                <div class="span12">
                    <div class="pull-right">
                        <label title="{{form.in_progress.help_text}}" for="id_in_progress" class="add-on">
                            Mark this list as still in progress:
                        </label>

                        {{form.in_progress}}

                        <button id="submit-qa" type="submit" class="btn btn-primary">Submit QA Results</button>
                    </div>
                </div>
            </div>
        </form>

                <div id="progress"> <div class="bar" style="width: 0%; height:30px; background-color:red;"></div> </div>

    </div>
</div>


{% endblock %}

{% block end_body_extra_script %}
    <script src="{% static "js/qa.js" %}?v={{VERSION}}"></script>
    <script src="{% static "datepicker/js/bootstrap-datepicker.js" %}?v={{VERSION}}"></script>
    <script src="{% static "js/jquery.ui.widget.js" %}"></script>
    <script src="{% static "js/jquery.iframe-transport.js" %}"></script>
    <script src="{% static "js/jquery.fileupload.js" %}"></script>
{% endblock %}